// Webny - Generator Starter HTML5 Canvas Game
(() => {
  const generateBtn = document.getElementById('generate');
  const downloadsSection = document.getElementById('downloads');
  const btnsContainer = document.getElementById('downloadBtns');

  // Templates builder
  function buildTemplates(opts) {
    const w = parseInt(opts.width) || 800;
    const h = parseInt(opts.height) || 600;
    const fps = parseInt(opts.fps) || 60;
    const genre = opts.genre || 'Dodge the Blocks';
    const title = opts.title || 'Dodge the Blocks';

    // index.html
    const indexHtml = `<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>${title}</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <canvas id="gameCanvas" width="${w}" height="${h}"></canvas>
  <script src="main.js"></script>
</body>
</html>`;

    // main.js (starter)
    const mainJs = `// Starter: ${title} - Genre: ${genre}
(function(){
  const GAME_WIDTH = ${w};
  const GAME_HEIGHT = ${h};
  const FPS_TARGET = ${fps};
  const GENRE = "${genre}";

  const canvas = document.getElementById('gameCanvas');
  const ctx = canvas.getContext('2d');
  canvas.width = GAME_WIDTH;
  canvas.height = GAME_HEIGHT;
  ctx.font = '16px sans-serif';

  // Player
  const player = { x: 50, y: GAME_HEIGHT - 60, w: 40, h: 40 };
  const blocks = [];
  let spawnTimer = 0;
  let score = 0;
  let gameOver = false;
  let last = performance.now();
  const keys = {};
  window.addEventListener('keydown', (e) => { keys[e.key] = true; });
  window.addEventListener('keyup', (e) => { keys[e.key] = false; });

  function spawnBlock(){
    blocks.push({ x: Math.random() * (GAME_WIDTH - 40), y: -20, w: 40, h: 40, vy: 2 + Math.random()*3 });
  }

  function rectsOverlap(a,b){
    return a.x < b.x + b.w && a.x + a.w > b.x && a.y < b.y + b.h && a.y + a.h > b.y;
  }

  function update(dt){
    if (keys['ArrowLeft'] || keys['a'] || keys['A']) player.x -= 250 * dt;
    if (keys['ArrowRight'] || keys['d'] || keys['D']) player.x += 250 * dt;
    if (player.x < 0) player.x = 0;
    if (player.x + player.w > GAME_WIDTH) player.x = GAME_WIDTH - player.w;

    spawnTimer += dt;
    if (spawnTimer > 0.8) { spawnBlock(); spawnTimer = 0; }

    for (const b of blocks) b.y += b.vy;
    for (let i = blocks.length - 1; i >= 0; i--) {
      if (rectsOverlap(player, blocks[i])) { gameOver = true; break; }
      if (blocks[i].y > GAME_HEIGHT) { blocks.splice(i,1); score++; }
    }
  }

  function draw(){
    // background
    ctx.fillStyle = '#87ceeb';
    ctx.fillRect(0, 0, GAME_WIDTH, GAME_HEIGHT);
    // player
    ctx.fillStyle = '#0a0';
    ctx.fillRect(player.x, player.y, player.w, player.h);
    // blocks
    ctx.fillStyle = '#e00';
    for (const b of blocks) ctx.fillRect(b.x, b.y, b.w, b.h);
    // HUD
    ctx.fillStyle = '#000';
    ctx.fillText('Score: ' + score, 10, 20);
    if (gameOver) {
      ctx.fillStyle = 'rgba(0,0,0,.5)';
      ctx.fillRect(0,0,GAME_WIDTH,GAME_HEIGHT);
      ctx.fillStyle = '#fff';
      ctx.fillText('Game Over. Muat ulang untuk restart.', 20, GAME_HEIGHT/2);
    }
  }

  function loop(now){
    const dt = Math.min(0.05, (now - last) / 1000);
    last = now;
    if (!gameOver) update(dt);
    draw();
    requestAnimationFrame(loop);
  }

  window.addEventListener('load', () => {
    canvas.focus();
    requestAnimationFrame(loop);
  });
})();`;

    // style.css
    const styleCss = `html, body { height: 100%; }
body { margin: 0; display: flex; align-items: center; justify-content: center; min-height: 100%; background: #f0f2f5; }
#gameCanvas { border: 1px solid #333; background: #000; display: block; }
`;

    // README.md
    const readmeMd = `# ${title}

Starter HTML5 Canvas game project generated by Webny.

Details
- Genre: ${genre}
- Resolution: ${w}x${h}
- FPS: ${fps}

How to run
1. Simpan file-file berikut di satu folder:
   - index.html
   - main.js
   - style.css
2. Buka index.html di browser modern (Chrome/Firefox/Safari).

Notes
- This starter includes a minimal "Dodge the Blocks" mechanic. Sesuaikan logika game sesuai genre yang dipilih.
- Untuk pengembangan lebih lanjut, tambahkan kelas pemain, musuh, fisika, level, dan UI sesuai kebutuhan.
`;

    return { indexHtml, mainJs, styleCss, readmeMd };
  }

  function downloadFile(filename, content, mime) {
    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.style.display = 'none';
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }

  generateBtn.addEventListener('click', () => {
    const title = document.getElementById('title').value || 'Dodge the Blocks';
    const genre = document.getElementById('genre').value;
    const width = document.getElementById('width').value || 800;
    const height = document.getElementById('height').value || 600;
    const fps = document.getElementById('fps').value || 60;

    const templates = buildTemplates({ title, genre, width, height, fps });

    // Update download UI
    btnsContainer.innerHTML = '';
    const files = [
      { name: 'index.html', mime: 'text/html', content: templates.indexHtml },
      { name: 'main.js', mime: 'application/javascript', content: templates.mainJs },
      { name: 'style.css', mime: 'text/css', content: templates.styleCss },
      { name: 'README.md', mime: 'text/markdown', content: templates.readmeMd },
    ];

    files.forEach(f => {
      const btn = document.createElement('button');
      btn.textContent = 'Download ' + f.name;
      btn.addEventListener('click', () => downloadFile(f.name, f.content, f.mime));
      btnsContainer.appendChild(btn);
    });

    downloadsSection.hidden = false;
  });
})();
